generations = 50

max_reproductions = 200

bnf_file_path = "data/sensible_market.bnf"
best_strategy = "( ( $PRICE / $FUNDAMENTAL ) > 1.1 ) ? ( \" SELL 9 \" ) : ( ( $PRICE > $PRICE ) ? ( \" BUY 6 \" ) : ( \" HOLD \" ) )"

[market]
initial_funds = 1500.0
initial_price = 100.0
initial_holdings = 15
rounds_per_generation = 100
noise_orders_per_round = 280
sims_per_generation = 20
fundamental_value_changes_per_simulation = 1
demand_push_coefficient = 0.2
fundamental_pull_coefficient = 0.01 
rsi_period = 14
atr_period = 20
sma_period = 14
risk_free_rate = 0.0

# Population Settings
[population]
size = 100
mutation_rate = 0.1
crossover_rate = 0.6
max_depth = 20
gene_length = 100
tournament_size = 7
elite_count = 20
cache_boolean = false
