generations = 50

max_genes = 48

bnf_file_path = "data/market.bnf"

[market]
initial_funds = 1000.0
initial_price = 100.0
initial_holdings = 0
rounds_per_generation = 500

# Population Settings
[population]
size = 500
mutation_rate = 0.8
crossover_rate = 0.2
gene_length = 100
tournament_size = 7
elite_count = 10
cache_boolean = false
